# Generated by Django 3.2 on 2022-05-10 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_bag_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='order_smallest_to_largest',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
