# Generated by Django 3.2 on 2022-05-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_charm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='sku',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='charm',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
