# Generated by Django 3.2 on 2022-05-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220528_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='sku',
            field=models.CharField(default='sku', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
